name: Build Short CV

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    
    - name: LaTeX compilation - Short CV
      uses: dante-ev/latex-action@v0.2.0
      with:
        root_file: cv.tex
        working_directory: short/
        args: -xelatex -file-line-error -interaction=nonstopmode
        compiler: latexmk
        
    - name: Publish CV
      uses: actions/upload-artifact@v1
      with:
        name: CV
        path: short/cv.pdf
