name: CI build

on: [push]

jobs:
  build:
    name: Build all CVs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    
    - name: Build short CV
      uses: dante-ev/latex-action@v0.2.0
      with:
        root_file: cv.tex
        working_directory: short/
        args: -xelatex -file-line-error -interaction=nonstopmode
        compiler: latexmk

    - name: Build long CV
      uses: dante-ev/latex-action@v0.2.0
      with:
        root_file: resume.tex
        working_directory: long/
        compiler: latexmk

    - name: Copy CVs for publishing
      run: |
        mkdir cvs
        cp short/cv.pdf cvs/short.pdf
        cp long/resume.pdf cvs/long.pdf
      shell: bash
        
    - name: Publish CVs to build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: CVs
        path: cvs/
