name: Publish all CVs

on: 
  push:
    branches:
      - master

jobs:
  build:
    name: Release latest CVs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    
    - name: Build CV
      uses: dante-ev/latex-action@v0.2.0
      with:
        root_file: cv.tex
        working_directory: ./
        args: -xelatex -file-line-error -interaction=nonstopmode
        compiler: latexmk
    
    - name: Build Web3 CV
      uses: dante-ev/latex-action@v0.2.0
      with:
        root_file: cv-web3.tex
        working_directory: ./
        args: -xelatex -file-line-error -interaction=nonstopmode
        compiler: latexmk
        
    - name: Format current date
      id: format_date
      run: echo "::set-output name=date::$(date +"%B %d, %Y")"

    - name: Release CVs
      uses: softprops/action-gh-release@v1
      with:
        name: CVs as of ${{ steps.format_date.outputs.date }}
        files: '*.pdf'
